language: ruby
rvm:
  - 2.2.5
  - 2.3.1
script:
  - bundle exec rake
before_script:
  - bundle exec rake findingaids:jetty:install
  - bundle exec rake jetty:start
  - sleep 10
after_script:
  - bundle exec rake jetty:stop
